### ISSUE TITLE
Implement Singly Linked List in C++

### ISSUE THREAD

**Issue by Jaideep25-tech** [Jaideep25-tech/DATA-STRUCTURES-AND-ALGORITHMS#2]

**Comment by motasimmakki** [comment]
@Jaideep25-tech  Kindly assign this to me.

**Comment by Jaideep25-tech** [comment]
> @Jaideep25-tech Kindly assign this to me, and as it is under Hacktoberfest, kindly add the label too. 🎈

sure you can work on it now. Assigned

**Comment by motasimmakki** [comment]
@Jaideep25-tech Kindly review PR #17

**Comment by Jaideep25-tech** [comment]
> @Jaideep25-tech Kindly review PR #17

merged
