### ISSUE TITLE
Implement singly linked list in C++

### ISSUE THREAD

**Issue by Jaideep25-tech** [Jaideep25-tech/DATA-STRUCTURES-AND-ALGORITHMS#4]

**Comment by arp99** [comment]
Please assign me this issue @Jaideep25-tech

**Comment by guptaushma** [comment]
Please assign this issue to me @Jaideep25-tech

**Comment by Jaideep25-tech** [comment]
> Please assign me this issue @Jaideep25-tech , and also mention which folder to edit

bro take other issue or create one new in which ever you want to contribute it may be any data structure or algorithm

**Comment by Jaideep25-tech** [comment]
> Please assign me this issue @Jaideep25-tech , and also mention which folder to edit

sorry for this one bro
